import Head from 'next/head'

type HeadMetaProps = {
  title: string
  description?: string
}

export const HeadMeta = ({ title, description }: HeadMetaProps) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="decscription" content={description || 'Generated by create context app'} />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
