import React from 'react'

import Head from 'next/head'

const SignUp = () => {
  return (
    <>
      <Head>
        <title>Sign-up</title>
        <meta name="decscription" content="Generated by create context app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>sign up</main>
    </>
  )
}

export default SignUp
